### ISSUE TITLE
Error running Recall Knowledge (Esoteric Lore) macro since pf2e 5.9.1

### ISSUE THREAD

**Issue by S-North** [mysurvive/pf2e-thaum-vuln#74]
Error occurs when GM clicks the Roll button in form triggered by player.
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/8228899/3e32bf7d-65a8-4eec-af77-32e8fe3e2145)

```js
commons.js:2536 Uncaught (in promise) TypeError: undefined. key.split is not a function or its return value is not iterable
[Detected 2 packages: system:pf2e, pf2e-thaum-vuln]
    at Object.getProperty (commons.js:2536:24)
    at Localization.localize (foundry.js:7585:27)
    at traitSlugToObject (pf2e.mjs:1:29782)
    at pf2e.mjs:61:1461
    at Array.map (<anonymous>)
    at #createTagFlavor (pf2e.mjs:61:1454)
    at pf2e.mjs:60:42709
    at async CheckPF2e.roll (pf2e.mjs:60:42499)
    at async Dialog.callback (socket.js:293:9)
getProperty @ commons.js:2536
localize @ foundry.js:7585
traitSlugToObject @ pf2e.mjs:1
(anonymous) @ pf2e.mjs:61
#createTagFlavor @ pf2e.mjs:61
(anonymous) @ pf2e.mjs:60
await in (anonymous) (async)
submit @ foundry.js:65212
_onClickButton @ foundry.js:65140
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Comment by mysurvive** [comment]
Should be fixed on latest. Thanks for the report.

**Comment by S-North** [comment]
Just tested it, all working perfectly now. Thanks for the great module.
